server:
  port: 0
spring:
  redis:
    cluster:
      nodes: ${mqtt.kvrocks.cluster.nodes}
      max-redirects: ${mqtt.kvrocks.cluster.max-redirects}
    password: ${mqtt.kvrocks.password}
    lettuce:
      pool:
        min-idle: ${mqtt.kvrocks.pool.min-idle:12}
        max-active: ${mqtt.kvrocks.pool.max-active:12}
        max-idle: ${mqtt.kvrocks.pool.max-idle:12}
        max-wait: ${mqtt.kvrocks.pool.max-wait:-1}
        time-between-eviction-runs: ${mqtt.kvrocks.pool.time-between-eviction-runs:-1}