mqtt:
  server:
    mode: aliyun
    is-use-epoll: false
    is-open-ssl: false
    ssl-certificate-password: ""
    ssl-certificate-path: ""
    tcp-port: 8081
    websocket-port: 8082
    api-port: 8083
    websocket-path: "/websocket"
    authentication-url: ""
    listener-pool-size: 10
    deal-message-thread-pool-size: 10
    aliyun:
      auth-way: token
      data-transfer:
        rocket-mq:
          name-server: 127.0.0.1
        input-rule-list:
          - from-topic: a
            to-topic: b
          - from-topic: c
            to-topic: d
        output-rule-list:
          - from-topic: a
            to-topic: b
  kvrocks:
    password:
    pool:
      min-idle: 12
      max-active: 12
      max-idle: 12
      max-wait: -1
      time-between-eviction-runs: -1
    cluster:
      nodes: 121.199.21.5:6666,47.98.117.35:6666
      max-redirects: 2

